baseURL = "https://www.uphouseworks.com"
languageCode = "en-us"
title = "Uphouseworks"
description = "An early build of the new UPHW website."
[params]
  copyright = "Copyright &copy; Benjamin Friedman Wilson 2021"
  author = "Benjamin Friedman Wilson"
  description = "An early build of the new UPHW website."
  themeColor = "#ffffff"
  twitterCard = "summary_large_image"
  twitterSite = "@uphouseworks"
  twitterCreator = "@mxbdev"
  twitterImage = "images/og_image.png"
  facebookLink = "https://www.facebook.com/uphouseworks"
  twitterLink = "https://twitter.com/uphouseworks"
